kumuluzee:
  name: rso-comment
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/CommentsDS
      connection-url: jdbc:postgresql://sl-eu-gb-p01.dblayer.com:15799/compose
      username: admin
      password: YODKTDTRRFSENICI
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://localhost:2379
