kumuluzee:
  name: rso-images
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
  - jndi-name: jdbc/ImagesDS
    connection-url: jdbc:postgresql://sl-eu-gb-p01.dblayer.com:15799/compose
    username: admin
    password: YODKTDTRRFSENICI
    max-pool-size: 20
  config:
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
  metrics:
    web-instrumentation:
    - name: images-endpoint
      url-pattern: /v1/images/*
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/ImagesDS
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                      <Configuration name="images">
                          <Appenders>
                              <Console name="console" target="SYSTEM_OUT">
                                  <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                              </Console>
                              <Socket name="logstash" host="a6342e20-69cf-4c17-af18-9a3fbd144772-ls.logit.io"
                              port="20625" protocol="tcp">
                                  <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                              </Socket>
                          </Appenders>
                          <Loggers>
                              <!-- Default logger -->
                              <Root level="all">
                                  <AppenderRef ref="console" level="info"/>
                                  <AppenderRef ref="logstash" level="trace"/>
                              </Root>
                          </Loggers>
                      </Configuration>'
app-properties:
  external-services:
    enabled: true
  healthy: true